spring.application.name=crudeDemo
spring.datasource.url=jdbc:mysql://localhost:3306/crudeDemo
spring.datasource.username=root
<<<<<<< HEAD
spring.datasource.password=YOUR_PASSWORD
spring.jpa.hibernate.ddl-auto=update
=======
spring.datasource.password=YOUR_MYSQL_PASSWORD
spring.jpa.hibernate.ddl-auto=update
>>>>>>> 4b62841 (Add new changes validation and Exception handling with DTOs)
